# Generated by Django 4.2 on 2023-04-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='product_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
            preserve_default=False,
        ),
    ]
