# Generated by Django 4.2 on 2023-04-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0020_remove_additem_history_history_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='additem',
            name='History',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.history'),
            preserve_default=False,
        ),
    ]
