# Generated by Django 4.2 on 2023-04-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_remove_additem_history_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='history',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='productHistory',
        ),
    ]
